controller_frequency: 1.0

TrajectoryPlannerROS:
  max_vel_x: 0.25
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 1
  acc_lim_x: 1
  acc_lim_y: 1

  holonomic_robot: false
  xy_goal_tolerance: 0.20
  yaw_goal_tolerance: 0.5

