obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.069
inflation_radius: 0.55

controller_frequency: 5

#observation_sources: laser_scan_sensor point_cloud_sensor
observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /robosar_agent_bringup_launch/agent1/feedback/scan, marking: true, clearing: true}

#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: topic_name, marking: true, clearing: true}
