global_costmap:
  global_frame: agent1/odom
  robot_base_frame: agent1/base_link
  update_frequency: 5.0
  static_map: true
  map_topic: /map
  origin_x: -50
  origin_y: -50
  width: 100
  height: 100

  # obstacle_layer:
  #   enabled: True
  
  # observation_sources: scan
  # scan:
  #   topic: /robosar_agent_bringup_launch/agent1/feedback/scan
  #   max_obstacle_height: 2.0
  #   clearing: True
  #   marking: True
  # plugins:
  #   - {name: static,                  type: "costmap_2d::StaticLayer"}
  #   - {name: obstacles_laser,         type: "costmap_2d::VoxelLayer"}
  #   - {name: inflation,               type: "costmap_2d::InflationLayer"}